Gym_Management/Models/Management/Workout.cs
using Gym_Management.Validators;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Gym_Management.Models.Management
{
    public class Workout
    {
        [Key]
        public int Id { get; set; }
        //public int WorkoutId { get; set; }
        [Required]
        [StringLength(70)]
        public string Name { get; set; }
        
        [Display(Name = "Type")]
        public WorkoutType WorkoutType { get; set; }
        public int WorkoutTypeId { get; set; }
        [Required]
        [Display(Name = "From")]
        [WorkoutDateTimeValidationToFuture]
        public DateTime StartDateTime { get; set; }
        [Required]
        [Display(Name = "To")]
        [WorkoutDateTimeValidationToFuture]
        public DateTime EndDateTime { get; set; }
        public Coach Coach { get; set; }
        public int CoachId { get; set; }
        //public ICollection<Customer> Customers { get; set; } = new HashSet<Customer>();
        [Required]
        public decimal? Capacity { get; set; }
        [Display(Name = "Customers")]
        public ICollection<Customer_Workout> Customer_Workouts { get; set; } = new HashSet<Customer_Workout>();
    }
}

Gym_Management/Models/Management/WorkoutType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Gym_Management.Models.Management
{
    public class WorkoutType
    {
        [Key]
        public int Id { get; set; }
        
        [StringLength(20)]
        public string Name { get; set; }
    }
}

Gym_Management/Models/Management/WorkoutViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gym_Management.Models.Management
{
    public class WorkoutViewModel
    {
        public Workout Workout { get; set; }
        public IEnumerable<WorkoutType> WorkoutTypesSelectList { get; set; }
        public IEnumerable<Coach> CoachesSelectList { get; set; }
    }
}

Gym_Management/Controllers/Management/WorkoutController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using Gym_Management.Models;
using Gym_Management.Models.Management;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.VisualBasic.ApplicationServices;

namespace Gym_Management.Controllers.Management
{
    public class WorkoutController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        // GET: Workout
        public ActionResult Index()
        {
            this.PrepareCoach();
            this.PrepareCustomers();
            this.PrepareWorkoutTypes();
            return View(db.Workouts.ToList());
        }
        private void PrepareCustomers()
        {
            var signedList = db.CustomersOnWorkouts.ToList();
            var customers = db.Customers.ToList();
            var workouts = db.Workouts.ToList();
            var list = new List<Customer_Workout>();
            foreach (var item in signedList)
            {
                var workout = workouts.Where(i => i.Id == item.WorkoutId).SingleOrDefault();
                var customer = customers.Where(i => i.Id == item.CustomerId).SingleOrDefault();
                if (customer != null)
                {
                    if (!customers.Contains(customer))
                    {
                        var CustomerOnWorkout = new Customer_Workout()
                        {
                            CustomerId = customer.Id,
                            Customer = customer,
                            WorkoutId = workout.Id,
                            Workout = workout

                        };
                        list.Add(CustomerOnWorkout);
                        workout.Customer_Workouts = list;
                    }
                }

            }
            db.SaveChanges();

            //var customer = db.Customers.Where(x => x.Id == signed.CustomerId).FirstOrDefault();
            //db.Workouts.FirstOrDefault().Customers.Add(customer);
        }
        
        private void PrepareWorkoutTypes()
        {
            var wtypes = db.WorkoutTypes.ToList();
            var workouts = db.Workouts.ToList();
            foreach (var item in workouts)
            {

                var wtype = wtypes.Where(i => i.Id == item.WorkoutTypeId).SingleOrDefault();
                if (wtype != null)
                {
                    item.WorkoutType = wtype;
                }

            }

        }
        private void PrepareCoach()
        {
            var coaches = db.Coaches.ToList();
            var workouts = db.Workouts.ToList();
            foreach (var item in workouts)
            {

                var coach = coaches.Where(i => i.Id == item.CoachId).SingleOrDefault();
                if (coach != null)
                {
                    item.Coach = coach;
                }

            }
        }
        // GET: Workout/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            this.PrepareCoach();
            this.PrepareCustomers();
            this.PrepareWorkoutTypes();
            Workout workout = db.Workouts.Find(id);
            if (workout == null)
            {
                return HttpNotFound();
            }
            return View(workout);
        }

        public ActionResult SignOutCustomer(int id)
        {
            this.PrepareCustomers();
            var userName = User.Identity.Name;
            var customer = db.Customers.ToList().Where(x => x.Email == userName).SingleOrDefault();
            var workout = db.Workouts.Find(id);
            var customerToWorkout = db.CustomersOnWorkouts;
            var CustomerOnWorkout = new Customer_Workout()
            {
                CustomerId = customer.Id,
                Customer = customer,
                WorkoutId = workout.Id,
                Workout = workout
            };
            var check = workout.Customer_Workouts.Where(x => x.CustomerId == customer.Id && x.WorkoutId == workout.Id).SingleOrDefault();
            var check2 = customerToWorkout.Where(x => x.CustomerId == customer.Id && x.WorkoutId == workout.Id).SingleOrDefault();
            if (check != check2)
            {
                return RedirectToAction("Index", db.Workouts.ToList());
            }
            else
            {
                var signedCustomerToWorkout = customerToWorkout.Where(x => x.CustomerId == customer.Id && x.WorkoutId == workout.Id).FirstOrDefault();
                if (signedCustomerToWorkout != null)
                {
                    workout.Capacity++;
                    workout.Customer_Workouts.Remove(CustomerOnWorkout);
                    customerToWorkout.Remove(signedCustomerToWorkout);
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Index", db.Workouts.ToList());
        }
        public ActionResult SignCustomer(int id)
        {
            this.PrepareCustomers();
            var userName = User.Identity.Name;
            var customer = db.Customers.ToList().Where(x => x.Email == userName).SingleOrDefault();
            var workout = db.Workouts.Find(id);
            var customerToWorkout = db.CustomersOnWorkouts;
            var CustomerOnWorkout = new Customer_Workout()
            {
                CustomerId = customer.Id,
                Customer = customer,
                WorkoutId = workout.Id,
                Workout = workout
            };
            var check = workout.Customer_Workouts.Where(x => x.CustomerId == customer.Id && x.WorkoutId == workout.Id).SingleOrDefault();
            var check2 = customerToWorkout.Where(x => x.CustomerId == customer.Id && x.WorkoutId == workout.Id).SingleOrDefault();
            if (check == check2 && check != null && check2 != null)
            {
                return RedirectToAction("Index", db.Workouts.ToList());
            }
            else
            {
                if (workout.Capacity != 0)
                {
                    workout.Capacity--;
                    workout.Customer_Workouts.Add(CustomerOnWorkout);
                    customerToWorkout.Add(CustomerOnWorkout);
                    db.SaveChanges();
                }
            }

            
            
            return RedirectToAction("Index", db.Workouts.ToList());
        }
        // GET: Workout/Create
        public ActionResult Create()
        {
            var model = this.SetViewModel();
            return View(model);
        }
        private WorkoutViewModel SetViewModel()
        {
            WorkoutViewModel model = new WorkoutViewModel();

            model.CoachesSelectList = db.Coaches.ToList();
            model.WorkoutTypesSelectList = db.WorkoutTypes.ToList();
            return model;
        }

        // POST: Workout/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Workout workout)
        {
            if (ModelState.IsValid)
            {
                var coach = db.Coaches.Where(x => x.Id == workout.CoachId).SingleOrDefault();
                var wtype = db.WorkoutTypes.Where(x => x.Id == workout.WorkoutTypeId).SingleOrDefault();
                workout.Coach = coach;
                workout.WorkoutType = wtype;
                db.Workouts.Add(workout);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            WorkoutViewModel model = new WorkoutViewModel();

            model.CoachesSelectList = db.Coaches.ToList();
            model.WorkoutTypesSelectList = db.WorkoutTypes.ToList();
            model.Workout = workout;
            return View(model);
        }

        // GET: Workout/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var model = SetViewModel();
            model.Workout = db.Workouts.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View(model);
        }

        // POST: Workout/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Workout workout)
        {
            if (ModelState.IsValid)
            {
                db.Entry(workout).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(workout);
        }

        // GET: Workout/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Workout workout = db.Workouts.Find(id);
            if (workout == null)
            {
                return HttpNotFound();
            }
            return View(workout);
        }

        // POST: Workout/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //var signedCustomers = db.SignedCustomerToWorkouts.Where(x => x.WorkoutId == id).FirstOrDefault();
            //var customer = db.Customers.ToList().Where(x => x.Id == id).SingleOrDefault();

Gym_Management/Views/Workout/Create.cshtml
@model Gym_Management.Models.Management.WorkoutViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Workout</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Workout.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Workout.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Workout.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Workout.StartDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class='input-group date' id='datetimepickerFrom'>
                @Html.EditorFor(model => model.Workout.StartDateTime, new { htmlAttributes = new { @class = "form-control" } })
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>

            @Html.ValidationMessageFor(model => model.Workout.StartDateTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Workout.EndDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class='input-group date' id='datetimepickerTo'>
                @Html.EditorFor(model => model.Workout.EndDateTime, new { htmlAttributes = new { @class = "form-control" } })
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>

            @Html.ValidationMessageFor(model => model.Workout.EndDateTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Workout.Capacity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Workout.Capacity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Workout.Capacity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Workout.Coach.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Workout.CoachId, new SelectList(Model.CoachesSelectList, "Id", "Name"), "Select Coach ...", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Workout.CoachId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Workout.WorkoutType.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Workout.WorkoutTypeId, new SelectList(Model.WorkoutTypesSelectList, "Id", "Name"), "Select Workout type ...", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Workout.WorkoutTypeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div class="action-link-button">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $.validator.methods.date = function (value, element) {
                return this.optional(element) || moment(value, "DD. MM. YYYY HH:mm", true).isValid();
            }
            $('#datetimepickerFrom').datetimepicker({
                format: 'DD. MM. YYYY HH:mm'
            });
            $('#datetimepickerTo').datetimepicker({
                format: 'DD. MM. YYYY HH:mm'
            });

        });

    </script>

}

Gym_Management/Views/Workout/Delete.cshtml
@model Gym_Management.Models.Management.Workout

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Workout</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacity)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="action-link-button">

            @Html.ActionLink("Back to List", "Index")
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
</div>

Gym_Management/Views/Workout/Details.cshtml
@model Gym_Management.Models.Management.Workout

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Workout</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Coach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Coach.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Customer_Workouts)
        </dt>

        <dd>
            @foreach (var item in Model.Customer_Workouts)
            {
                @Html.FormatValue(Html.DisplayFor(model => item.Customer.Name), "{0} ")
            }

        </dd>

    </dl>
</div>
<div class="action-link-button">
    @Html.ActionLink("Back to List", "Index")
    @if (User.IsInRole(Gym_Management.Constants.Roles.Admin))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id })

    }

</div>

Gym_Management/Views/Workout/Edit.cshtml
@model Gym_Management.Models.Management.WorkoutViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Workout</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Workout.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Workout.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Workout.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Workout.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Workout.StartDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class='input-group date' id='datetimepickerFrom'>
                @Html.EditorFor(model => model.Workout.StartDateTime, new { htmlAttributes = new { @class = "form-control" } })
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>

            @Html.ValidationMessageFor(model => model.Workout.StartDateTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Workout.EndDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class='input-group date' id='datetimepickerTo'>
                @Html.EditorFor(model => model.Workout.EndDateTime, new { htmlAttributes = new { @class = "form-control" } })
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>

            @Html.ValidationMessageFor(model => model.Workout.EndDateTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Workout.Capacity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Workout.Capacity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Workout.Capacity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Workout.Coach.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Workout.CoachId, new SelectList(Model.CoachesSelectList, "Id", "Name"), "Select Coach ...", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Workout.CoachId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Workout.WorkoutType.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Workout.WorkoutTypeId, new SelectList(Model.WorkoutTypesSelectList, "Id", "Name"), "Select Workout type ...", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Workout.WorkoutTypeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div class="action-link-button">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
        $(document).ready(function () {
            $.validator.methods.date = function (value, element) {
                return this.optional(element) || moment(value, "DD. MM. YYYY HH:mm", true).isValid();
            }
            $('#datetimepickerFrom').datetimepicker({
                format: 'DD. MM. YYYY HH:mm'
            });
            $('#datetimepickerTo').datetimepicker({
                format: 'DD. MM. YYYY HH:mm'
            });

        });

</script>
}

Gym_Management/Views/Workout/Index.cshtml
@model IEnumerable<Gym_Management.Models.Management.Workout>

@{
    ViewBag.Title = "Workouts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>

    @if (User.IsInRole(Gym_Management.Constants.Roles.Admin))
    {
        <i class="fa fa-plus" aria-hidden="true"></i>
        @Html.ActionLink("Create New", "Create", "Workout", new { @class = "styled-action-link-button" })
    }
</p>
<table id="workout" class="styled-table table-bordered table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WorkoutType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Capacity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Coach)
            </th>
            <th>
                @Html.DisplayName("Customers")
            </th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr class="active-row">
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WorkoutType.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Capacity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Coach.Name)
            </td>
            <td>
                @if (item.Customer_Workouts != null)
                {
                    foreach (var customer in item.Customer_Workouts)
                    {
                        @Html.FormatValue(Html.DisplayFor(modelItem => customer.Customer.Name), "{0} ")
                    }
                }
            </td>
            <td>
                @if (User.IsInRole(Gym_Management.Constants.Roles.Admin))
                {
                    <i class="fa fa-pencil" aria-hidden="true"></i>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                    <i class="fa fa-search" aria-hidden="true"></i>
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                    <i class="fa fa-trash" aria-hidden="true"></i>
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                }
                else
                {
                    <i class="fa fa-plus" aria-hidden="true" &nbsp></i>
                    @Html.ActionLink("Sign in", "SignCustomer", new { id = item.Id })
                    <i class="fa fa-minus" aria-hidden="true" &nbsp></i>
                    @Html.ActionLink("Sign out", "SignOutCustomer", new { id = item.Id })
                    <i class="fa fa-search" aria-hidden="true" &nbsp></i>
                    @Html.ActionLink("Details", "Details", new { id = item.Id })

                }
            </td>
        </tr>
    }

</table>
@section scripts {
    <script>
        $(document).ready(function () {
            $("#workout").DataTable({
            });

        });
    </script>
}