Gym_Management/Controllers/Management/WorkoutTypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gym_Management.Models;
using Gym_Management.Models.Management;

namespace Gym_Management.Controllers.Management
{
    public class WorkoutTypeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: WorkoutType
        public ActionResult Index()
        {
            return View(db.WorkoutTypes.ToList());
        }
        public IEnumerable<WorkoutType> GetWorkoutTypes()
        {
            var list = db.WorkoutTypes.ToList();
            return list;
        }
        // GET: WorkoutType/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkoutType workoutType = db.WorkoutTypes.Find(id);
            if (workoutType == null)
            {
                return HttpNotFound();
            }
            return View(workoutType);
        }

        // GET: WorkoutType/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: WorkoutType/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] WorkoutType workoutType)
        {
            if (ModelState.IsValid)
            {
                db.WorkoutTypes.Add(workoutType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(workoutType);
        }

        // GET: WorkoutType/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkoutType workoutType = db.WorkoutTypes.Find(id);
            if (workoutType == null)
            {
                return HttpNotFound();
            }
            return View(workoutType);
        }

        // POST: WorkoutType/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] WorkoutType workoutType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(workoutType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(workoutType);
        }

        // GET: WorkoutType/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkoutType workoutType = db.WorkoutTypes.Find(id);
            if (workoutType == null)
            {
                return HttpNotFound();
            }
            return View(workoutType);
        }

        // POST: WorkoutType/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WorkoutType workoutType = db.WorkoutTypes.Find(id);
            db.WorkoutTypes.Remove(workoutType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gym_Management/Views/WorkoutType/Create.cshtml
@model Gym_Management.Models.Management.WorkoutType

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WorkoutType</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="action-link-button">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Gym_Management/Views/WorkoutType/Delete.cshtml
@model Gym_Management.Models.Management.WorkoutType

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WorkoutType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="action-link-button">

            @Html.ActionLink("Back to List", "Index")
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
</div>

Gym_Management/Views/WorkoutType/Details.cshtml
@model Gym_Management.Models.Management.WorkoutType

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>WorkoutType</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<div class="action-link-button">
    @Html.ActionLink("Back to List", "Index")
    @if (User.IsInRole(Gym_Management.Constants.Roles.Admin))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id })

    }

</div>

Gym_Management/Views/WorkoutType/Edit.cshtml
@model Gym_Management.Models.Management.WorkoutType

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WorkoutType</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="action-link-button">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Gym_Management/Views/WorkoutType/Index.cshtml
@model IEnumerable<Gym_Management.Models.Management.WorkoutType>

@{
    ViewBag.Title = "Workout types";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>
    
    @if (User.IsInRole(Gym_Management.Constants.Roles.Admin))
    {
        <i class="fa fa-plus" aria-hidden="true"></i>
        @Html.ActionLink("Create New", "Create", "WorkoutType", new { @class = "styled-action-link-button" })
    }
</p>
<table id="wtype" class="styled-table table-bordered table-hover table-responsive">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr class="active-row">
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @if (User.IsInRole(Gym_Management.Constants.Roles.Admin))
                {
                    <i class="fa fa-pencil" aria-hidden="true"></i>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                    <i class="fa fa-search" aria-hidden="true"></i>
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                    <i class="fa fa-trash" aria-hidden="true"></i>
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                }
                else
                {
                    <i class="fa fa-search" aria-hidden="true"></i>
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                }
            </td>
        </tr>
    }

</table>
@section scripts {
    <script>
        $(document).ready(function () {
            $("#wtype").DataTable();


        });
    </script>
}